# Generated by Django 4.2.3 on 2023-07-04 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20, verbose_name='用户名')),
                ('password', models.CharField(max_length=18, verbose_name='密码')),
                ('login_time', models.DateTimeField(null=True, verbose_name='登录时间')),
                ('email', models.CharField(max_length=40, verbose_name='邮箱')),
            ],
        ),
    ]
